"""
    Problem Statement :
       Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
       the first 10 terms will be:
                                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million,
        find the sum of the even-valued terms.
"""

def fib(n):
    a = 0
    b = 1
    sum = 0
    for i in range(2,n):
        a,b = b, a+b
        if a>n:
            break
        if a%2==0:
            sum+=a
    return sum

fib(4_000_000)
#4613732


